### ISSUE TITLE
TRAINING DATA

### ISSUE THREAD

**Issue by Saangetheya** [sola-da/NL2Type#1]
Hi Sir,
I am an Undergraduate CSE student studying in IIT Tirupati.
I have read your paper and found it very interesting. However, on trying to train the model I have run into some issues. Sir, it would be a huge help if you could provide me with the extracted data that could be fed into the model as an input which would enable me to study the paper thoroughly.

**Comment by michaelpradel** [comment]
Thanks for your interest. Have you tried to follow the instructions in the README, and if so, could you please be more precise about any problems you encounter? In particular, have you seen the "Download data" section of the README?

**Comment by Saangetheya** [comment]
Sir, thanks a lot for your response.
Yes Sir, I have downloaded all the required files and data including the training files and testing files.
Sir, however I am unsure how to convert the training files into the required format used to input into the model within the model_paper.h5 file. Sir, more precisely the extraction process of the training files is perplexing. Sir, I would like to know if there are any csv files obtained from the training dataset with which the model could be easily trained. 
I would like to train the model/model_paper.h5 however the README doesn't provide me with sufficient information about the same.

**Comment by michaelpradel** [comment]
The repository contains an already trained model (model_paper.h5), which you can apply either to the JS files used in the evaluation, or to any other JS file. Unfortunately, the code for training the model isn't available anymore. 

Let me point out that the NL2Type model has been superseeded anyway by a newer model in our follow-up TypeWriter work. You can find the paper on TypeWriter [here](https://software-lab.org/publications/fse2020_TypeWriter.pdf), and a re-implementation of its neural model [here](https://github.com/saltudelft/dl-type-python).

Hope that helps!

**Comment by Saangetheya** [comment]
Respected Sir,
I am sorry for the delayed response.
Sir, I have spent a lot of time studying the NL2Type model and have been thoroughly interested by the same. Sir, I have downloaded both the training files and the testing files (json). Sir, however I am unaware how to extract the data from the training json files into the 5 tuple representation, which would further be encoded and passed into the model for training. Sir, I have also observed the testing data used, "data/paper/raw_csv/test.csv" has been provided for testing the model , similarly, if the training data in the form of train.csv could be provided, it would be a huge help for me to complete my study on this paper.

**Comment by michaelpradel** [comment]
Since some of the code for extracting the training and for training the model is missing, unfortunately (see above), I cannot point you to an easy solution. If you nevertheless want to perform these two steps yourself, I recommend to have a look at jsdoc_extractor.py and jsdoc_to_csv.py, which look like they've served for extracting the training data. For the training, you could try to reimplement the code based on what you see in predict.py and in the paper.
